# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m75UwxwUx82FvybX7kodza5jIjjv8PA4
"""

#------------------------Header-------------------------

#Code by: Isaac Boyd, James Lucas 

##Code For: K-nearest neighbor
##Completed: 9-29-2022
##References: NA

#-----------------------imports-------------------------

import pandas as pd
import requests
import os
import random

#----Python Classes import----

classInputArray = [['https://github.com/IsaacBoyd2/ActualFactualML/blob/main/Project2/Code/preprocessing.py?raw=true','preprocessing.py'], 
                   ['https://github.com/IsaacBoyd2/ActualFactualML/blob/main/Project2/Code/model.py?raw=true','model.py']]

for i in range(len(classInputArray)):
  with open(classInputArray[i][1], 'w') as f:
    r = requests.get(classInputArray[i][0])
    f.write(r.text)

import preprocessing as pp
import model as classifier

#------------------------Main--------------------------

def main():

#-----Hyper_parameters-------#

  k_nn = 7
  xx = 2

#----------------------------#

  preProcess = pp.Preprocessing()
  preProcess.process()
  preProcess.fold()
  data = [preProcess.tuning, preProcess.folds]

  if xx == 1:
    modeling = classifier.Model()
    modeling.run(data,k_nn)

  if xx == 2:
    modeling = classifier.Model()
    modeling.run(data,k_nn)


#calls main
main()

#makes sure that the python classes are taken out
for i in range(len(classInputArray)):
  fileName = classInputArray[i][1]
  !rm fileName