# -*- coding: utf-8 -*-
"""Project 1 CSCI447

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yvLvnKktDHPw_-fmFtZOzQrGMf1lGPl1
"""

#import Pandas and Numpy

import pandas as pd
import numpy as np

#--------------------------------------
#Bring in the data

df = pd.read_csv('https://github.com/IsaacBoyd2/ActualFactualML/blob/c55c311d66e9dd04da9a6ee8627facdcc11e9d2a/DataProject1/glass.csv?raw=true')#, on_bad_lines='skip')

#--------------------------------------

#This should Probably be converted into a different dataframe instead of variables in order to make it more visual.

for i in range(1, max(df['Glass Type'])):                        #Reset the global variables on each run
  globals()[f"number_of_{i}s"] = 0

for i in range(1, max(df['Glass Type'])):                        #For all possible categories sum all of the categories and then divide
  for j in range(len(df)):                                       #by the length of the dataframe. Store these values in a variable.
    if df['Glass Type'][j] == i:                                 # --  Q(C = ci) = #{x ∈ ci}/N
      globals()[f"number_of_{i}s"] += 1
  globals()[f"Q{i}"] = globals()[f"number_of_{i}s"]/len(df)





  
print(Q1)
print(number_of_2s)